### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Susmita-Dey** [opensourcecommunity-hub/developer-portfolios#2]
Code of Conduct file is missing here. It needs to be added.

**Comment by Timonwa** [comment]
Hi @Susmita-Dey, can I work on this?

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey, can I work on this?

Yes, sure. Go ahead.

**Comment by Timonwa** [comment]
Ok. Thanks
