### ISSUE TITLE
Improving Card Design

### ISSUE THREAD

**Issue by soumali28** [opensourcecommunity-hub/developer-portfolios#21]
Improvise the card section given below with some latest design

![OpenSourceHub - Developer Portfolios - Google Chrome 05-08-2022 19_35_50](https://user-images.githubusercontent.com/66300439/183094293-3824a161-43b2-43c3-ac43-b988fea1a0f5.png)

**Comment by zugzwang03** [comment]
I want to work on this issue under SSOC'22
