### ISSUE TITLE
Implement Dark mode to the website

### ISSUE THREAD

**Issue by soumali28** [opensourcecommunity-hub/developer-portfolios#23]
- add a toggle button on the top right corner.
- implementing dark and light mode when click on the button

**Comment by nandinitrivedi05** [comment]
I would like to contribute to this issue!

**Comment by zugzwang03** [comment]
I can work on this under SSOC'22

**Comment by soumali28** [comment]
@zugzwang03 Whats the update on dark mode?

**Comment by zugzwang03** [comment]
Working on it, will require another day.
