### ISSUE TITLE
Improve UI of cards

### ISSUE THREAD

**Issue by con-artist** [opensourcecommunity-hub/developer-portfolios#29]
I would like to improve the UI of the cards in the page

**Comment by soumali28** [comment]
Hey its already done for the ui of the cards but u can suggest anu changes or design if it looks good i'll assign you.

**Comment by con-artist** [comment]
![image](https://user-images.githubusercontent.com/82517773/183951965-e0ad60db-043e-42e9-bf78-4b57e7161d39.png)
there is this issue in cards
its not centered properly
And I can improve the UI add border, shadow, hover effect etc

**Comment by soumali28** [comment]
@con-artist this is actually  being fixed and is merged  the website link is nkt updated u can clone and check it.

**Comment by SahilDahekar** [comment]
Can we create a landing page with background video and then a button that will redirect us to a page with all the developer portfolios and also on the portfolios page we and make a nice heading and these cards can be improved with the tech stack they are using and also thier individual git hub links and other social media links.

**Comment by SahilDahekar** [comment]
If so i would like to work on this issue

**Comment by soumali28** [comment]
I dont know abt this you should talk to the project admin for the approval
