### ISSUE TITLE
[BUG] : Texts are showing outside the box

### ISSUE THREAD

**Issue by PritamSarbajna** [opensourcecommunity-hub/developer-portfolios#31]
Hey when hovering completed the text are showing outside the box. Like this :

https://user-images.githubusercontent.com/90236635/184064254-44ab53e8-4442-4bf9-b47a-2f03e8b0714e.mp4

#### Solution :

I think a fade out animation can change it or I've to look on the code to actually able to tell possible optimal solution. You can assign it to me

**Comment by satyamkale27** [comment]
i want to work on this BUG please assign to me
