### ISSUE TITLE
Making a navbar and toggle button modification

### ISSUE THREAD

**Issue by soumali28** [opensourcecommunity-hub/developer-portfolios#34]
![OpenSourceHub - Developer Portfolios - Google Chrome 12-08-2022 15_10_34](https://user-images.githubusercontent.com/66300439/184328661-a5b70eab-9a53-451e-8d8d-69b408982f3f.png)
 - Make the title "Opensourcehub" and the toggle button in the same line i.e the navbar
 - Give the toggle button a modern look

**Comment by mridulpal019** [comment]
Hi !
I would like to work on this issue can you assign it to me?
