### ISSUE TITLE
Add a Header section after the navbar

### ISSUE THREAD

**Issue by soumali28** [opensourcecommunity-hub/developer-portfolios#49]
![Screenshot 2022-08-15 200749](https://user-images.githubusercontent.com/66300439/184656250-85cbdd82-f7fc-46b0-9984-b4cc2cbc02fc.png)
- create a header section after navbar
- give it a modern look
- add what this project is about in 2 to 3 lines
- you can add pictures too

**Comment by Soham-Chatterjee** [comment]
I want to take up this issue

**Comment by iamifechi** [comment]
I would love to take this up
