### ISSUE TITLE
changing button style

### ISSUE THREAD

**Issue by harshitjain156** [opensourcecommunity-hub/developer-portfolios#53]
Transforming button style

![image](https://user-images.githubusercontent.com/92665993/185437355-925d792e-560c-4b55-9e0d-71cf1a7ca58a.png)

![image](https://user-images.githubusercontent.com/92665993/185437333-cc42c6c2-2f45-42f8-91d2-03bcf1eca1c1.png)

**Comment by Soham-Chatterjee** [comment]
Would love to take this issue up

**Comment by Susmita-Dey** [comment]
@harshitjain156 What changes do you wanna make? Wanna add transition or change the UI?
There's already a PR with these kind of changes. 

Can you elaborate your idea a bit more?
