### ISSUE TITLE
Website Build

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [opensourcecommunity-hub/developer-portfolios#6]
Hi,

Have u any plan to create a static website?
This website will preview all the templates.

**Comment by Susmita-Dey** [comment]
> Have u any plan to create a static website? This website will preview all the templates.
Yes, I was planning to have one. Come on discord we'll work on it together.

**Comment by Programming-School-Pro-Coding** [comment]
> > Have u any plan to create a static website? This website will preview all the templates.
> > Yes, I was planning to have one. Come on discord we'll work on it together.

??

**Comment by Susmita-Dey** [comment]
@Programming-School-Pro-Coding Let's discuss it in our discord server

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding Let's discuss it in our discord server

No, In here or slack

**Comment by Susmita-Dey** [comment]
> > @Programming-School-Pro-Coding Let's discuss it in our discord server
> 
> No, In here or slack

Okay, let's head over to the discussions tab.

**Comment by Susmita-Dey** [comment]
This issue is moved to the [discussions](https://github.com/opensourcecommunity-hub/developer-portfolios/discussions/9) tab.
So, I'm closing it.
